package com.rest.bibliorest.enums;

public enum GenereLibro {

	ROMANZO, GIALLO, THRILLER, HORROR, FANTASCIENZA, FANTASY, DISTOPICO, AVVENTURA, STORICO, BIOGRAFIA, AUTOBIOGRAFIA,
	SAGGIO, POESIA, EROTICO, UMORISMO, DRAMMATICO, SPIONAGGIO, WESTERN, ROMANTICO, RELIGIOSO, FILOSOFICO, PSICOLOGICO,
	MITOLOGICO, POLIZIESCO, CLASSICO, YOUNG_ADULT, INFANZIA, TECNICO, SCIENTIFICO, MANUALISTICO, ARTISTICO,
	GASTRONOMICO, VIAGGI, ECONOMICO, POLITICO, SPORTIVO, NARRATIVO, FAVOLA, MISTERO, POETICO, SURREALE, SATIRA, MAGICO, MOTIVAZIONALE

}
